var texto="";
texto=document.getElementById('tipo').innerHTML+"\n";
texto=texto+document.getElementById('estimacion').innerHTML+"\n";
texto=texto+document.getElementById('acopio').innerHTML+"\n";
texto=texto+document.getElementById('acopiar').innerHTML+"\n";
$('#example').DataTable( {
    dom: 'Bfrtip',
    buttons: [
        'copyHtml5',
        'excelHtml5',
        'csvHtml5',
        {
            extend: 'pdfHtml5',
            text: 'PDFexport',
            customize: function ( doc ) {
                // Splice the image in after the header, but before the table
                doc.content.splice( 1, 0, {
                    margin: [ 0, 0, 0, 12 ],
                    text: texto,
                } );
                // Data URL generated by http://dataurl.net/#dataurlmaker
            }
        }
    ],
    "pageLength": 20
} );